# Generated by Django 5.1.6 on 2026-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_automationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
