# Generated by Django 4.2.20 on 2025-03-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.semester')),
            ],
        ),
        migrations.CreateModel(
            name='AssignSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.teacher')),
            ],
        ),
    ]
