# Generated by Django 4.2.20 on 2025-03-29 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.department')),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_attendance', to='subject.subject')),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_attendance', to='subject.subject')),
                ('p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3_attendance', to='subject.subject')),
                ('p4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p4_attendance', to='subject.subject')),
                ('p5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p5_attendance', to='subject.subject')),
                ('p6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p6_attendance', to='subject.subject')),
                ('p7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p7_attendance', to='subject.subject')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.teacher')),
            ],
        ),
    ]
