# Generated by Django 4.2.20 on 2025-03-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
    ]
